name: Deploy to Firebase Hosting on commit to main

on:
  push:
    branches:
      - main  # Triggers deployment when there's a commit to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js (update to at least version 18.x)
      - uses: actions/setup-node@v2
        with:
          node-version: '18'  # Updated Node.js version to meet Angular's requirements

      # Step 3: Change directory to Angular app
      - run: cd apps/angular-app

      # Step 4: Install dependencies (npm install)
      - run: npm install

      # Step 5: Build the Angular app using the local 'ng' binary
      - run: ./node_modules/.bin/ng build --configuration production

      # Step 6: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCOE_8A318 }}
          channelId: live
          projectId: scoe-8a318
