name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js (ensure it is installed)
      - uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust according to your Angular version's Node.js requirement

      # Step 3: Change directory to the Angular app folder
      - run: cd apps/angular-app

      # Step 4: Install dependencies and build the app
      - run: |
          npm install
          ng build --configuration production

      # Step 5: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCOE_8A318 }}
          channelId: live
          projectId: scoe-8a318
